### ISSUE TITLE
backward compatibility with RFC8345

### ISSUE THREAD

**Issue by bclaise** [OlgaHuawei/draft-olga-digital-map#15]
backward compatibility with RFC8345:  As discussed today, this is an additional requirement. Not too sure where to add it.

The section 4 "Digital Map Requirements" are actually generic, not related to RFC8345. 
If we append that section, it must be along the lines: "if RFC8345 is chosen as the starting point (see section 4.1), and RFC8345 needs to be improved, then the backward compatibility with RFC8345 is required."

The alternative is to add this in section 4.1, or even 4.2 (even though it doesn't mention RFC8345).

So not too sure where in the end.

**Comment by bclaise** [comment]
Actually, I like the new addition by Olga in section 5.1.x. All the gaps have a suggestion along the line of "We suggest to work on RFC8345 bis to provide the backward compatible way ..."
And I see what I wanted to see further down "Make backward compatible updates to RFC8345, work on RFC8345 bis"

We can close this one.

**Comment by OlgaHuawei** [comment]
Addressed in the latest version
