### ISSUE TITLE
Better describe the notion of layer

### ISSUE THREAD

**Issue by bclaise** [OlgaHuawei/draft-olga-digital-map#9]

**Comment by OlgaHuawei** [comment]
I added a sentence about the layers relevant for different users. The following is the latest definition:

<dt>Topology Layer -</dt>

<dd>Defines a layer in the multilayer topology. A multilayertopology models relationships between different layers ofconnectivity, where each layer represents a connectivity aspect ofthe network and service that needs to be configured, controlled andmonitored. The layer can also represent what needs to be managed by a specific user,for example IGP layer can be of interest to the user troubleshooting the routing,while the Optical Layer may be of interest to the user managing the Optical Network.Some topology layers may relate closely to OSI layers,like L1 topology for physical topology, L2 for link topology and L3for IPv4 and IPv6 Topologies. Some topology layers represent thecontrol aspects of L3, like OSPF, IS-IS and BGP. The top layerrepresents the service view of the connectivity, that can differ fordifferent types of services and for differentproviders/solutions.</dd>

**Comment by OlgaHuawei** [comment]
Added the better definition and reviewed by the authors
